"""Slide — Plan: The Sprint Archive (plan-summary.md)."""
# @guideline: minimalist-visual + maximize-viewport
from streamtex import *
from streamtex.enums import Tags as t
from custom.styles import Styles as s
from shared_widgets import st_hover_tooltip


class BlockStyles:
    """Plan summary slide styles."""
    heading = s.project.titles.heading
    body = s.project.titles.body
    label = s.project.titles.label
    closing = s.project.titles.body + s.project.colors.highlight + s.bold

bs = BlockStyles

_PLAN_SUMMARY_MD = """\
---
gse:
  id: PLN-001              # inherited from plan.yaml.id
  type: plan-summary
  sprint: 2
  status: done
---

# Sprint 2 — Plan Summary

**Goal:** Budget Alerts feature
**Mode:** full | **Budget:** 8 pts (8 consumed, 0 remaining)

## Tasks

| TASK     | Complexity | Final Status |
|----------|------------|--------------|
| TASK-010 | M          | delivered    |
| TASK-011 | S          | delivered    |

## Activity Flow

collect → assess → plan → reqs → design → tests
→ produce → review → [fix] → deliver

# [fix] runs only if review reports HIGH/MEDIUM findings;
# otherwise moved to workflow.skipped with reason 'no review findings'."""


def build():
    st_marker("plan-summary.md — Sprint Archive")
    with st_block(s.project.containers.page_fill_top):
        with st_zoom(90):
            st_write(bs.heading, "Plan: The Sprint Archive", tag=t.div, toc_lvl="+1")
        st_hover_tooltip(
            title="plan-summary.md — Read-only Archive",
            entries=[
                ("Trigger", "Generated by DELIVER Step 9 — Finalize, before setting plan.yaml.status = completed."),
                ("Read-only", "Never read by the orchestrator for decisions. Used for human reference, COMPOUND analysis, and sprint history."),
                ("ID inheritance", "The frontmatter inherits plan.yaml.id (PLN-NNN) into gse.id — preserves P6 traceability across the live → archive transition."),
                ("Content", "Goal, tasks delivered, activity flow (completed/skipped), scope changes, coherence alerts, risks."),
                ("Location", "docs/sprints/sprint-NN/plan-summary.md — one per sprint."),
            ],
            scale="2vw", width="70vw", position="center",
        )
        st_space("v", 0.5)

        with st_zoom(120):
            st_write(bs.body, (bs.label, "Example"), " — plan-summary.md at delivery:")
            st_space("v", 0.5)

            st_code(s.none, code=_PLAN_SUMMARY_MD, language="markdown")

            st_space("v", 0.5)
            with st_block(s.project.containers.callout):
                st_write(
                    bs.closing,
                    "Read-only · Generated by DELIVER · Inherits PLN-NNN for P6 traceability.",
                )
