"""Slide — Stat-hero: 5.2-21.7% hallucinated dependencies."""
# @guideline: maximize-viewport
# @pattern: stat-hero
from streamtex import *
from streamtex.bib import cite
from streamtex.enums import Tags as t
from custom.styles import Styles as s
from custom.config import IS_EDITABLE
from custom.prompts import AI_PREFIX as _PREFIX, AI_SUFFIX_PORTRAIT as _SUFFIX
from shared_widgets import st_hover_tooltip

class BlockStyles:
    """Hallucinated deps stat-hero styles."""
    heading = s.project.titles.slide_title + s.center_txt
    stat = s.project.titles.stat_hero
    body = s.project.titles.body
    keyword = s.bold + s.project.colors.highlight
    source = s.project.citation + s.large + s.center_txt
bs = BlockStyles

_PROMPT = (
    f"{_PREFIX} A package box icon in electric blue with a ghost-like phantom duplicate "
    "next to it in faint teal, both feeding into a supply chain arrow. The phantom "
    "package has an amber warning glow. Represents LLMs generating references to "
    f"non-existent packages that create supply-chain attack vectors. {_SUFFIX}"
)

def build():
    with st_block(s.project.containers.page_fill_top):
        with st_block(s.center_txt):
            st_write(bs.heading, "Phantom Packages", tag=t.div, toc_lvl="1")

            with st_grid(
                cols="2fr 3fr",
                gap="24px",
                cell_styles=s.project.containers.grid_cell_centered,
            ) as g:
                with g.cell():
                    st_image(
                        s.none,
                        width="80%",
                        editable=IS_EDITABLE,
                        name="vc_danger_halluc",
                        prompt=_PROMPT,
                        provider="openai",
                        ai_size="1024x1536",
                    )

                with g.cell():
                    with st_grid(
                        cols="95fr 5fr",
                        gap="0px",
                        cell_styles=s.project.containers.grid_cell_centered,
                    ) as sg:
                        with sg.cell():
                            with st_zoom(80):
                                st_write(bs.stat, "5.2\u201321.7%")
                        with sg.cell():
                            st_hover_tooltip(
                                title="About this statistic",
                                entries=[
                                    (
                                        "5.2%",
                                        "Average hallucination rate for commercial "
                                        "models (GPT-4, Claude, etc.).",
                                    ),
                                    (
                                        "21.7%",
                                        "Average hallucination rate for open-source "
                                        "models (Code Llama, StarCoder, etc.).",
                                    ),
                                    (
                                        "576,000 samples",
                                        "Python + JavaScript code generated by "
                                        "16 LLMs. 205,474 unique hallucinated "
                                        "package names identified.",
                                    ),
                                    (
                                        "Supply-chain attack",
                                        "LLMs generate import statements referencing "
                                        "packages that don\u2019t exist. An attacker "
                                        "registers these phantom names on PyPI/npm "
                                        "with malicious code. Any developer whose "
                                        "LLM generates the same phantom name "
                                        "unknowingly installs the attacker\u2019s "
                                        "package.",
                                    ),
                                ],
                                scale="2.2vw",
                                width="70vw",
                                position="left",
                            )
                    st_space("v", 1)
                    st_write(
                        bs.body,
                        "of package references generated by LLMs point to "
                        "non-existent packages.",
                    )
                    st_space("v", 1)
                    st_write(
                        bs.body,
                        (bs.keyword, "Supply-chain attack: "),
                        "adversaries upload malicious code under hallucinated "
                        "package names.",
                    )
                    st_space("v", 1)
                    # REF: https://arxiv.org/abs/2406.10279
                    st_write(bs.source, cite("spracklen-packages2025"))
                    st_write(bs.body, "Commercial vs open-source models.")
